### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by stdcoutzrh** [OliverRensu/Shunted-Transformer#11]
请问模型在2080ti cuda10.2上比3090 cuda11.3快很多可能是什么原因呢=-=

**Comment by OliverRensu** [comment]
有没有可能是io之类的问题呢？   或者负载太小体现不出3090的优势  理论上应该是3090更快

**Comment by stdcoutzrh** [comment]
> 

作者您好 感谢您的回复 后来我把3090上的pytorch升级到1.12就好了，似乎是pytorch1.10 和1.11都会慢

**Comment by stdcoutzrh** [comment]
似乎是pytorch版本的问题，原先是1.10，升级到1.12之后解决了。
