### ISSUE TITLE
About config

### ISSUE THREAD

**Issue by imcjx** [OliverRensu/Shunted-Transformer#6]
Thank you very much for your work. Is the parameters `drop_path` and `clip_grad` in the configuration file useless? they don't seem to be loaded into the model.

**Comment by OliverRensu** [comment]
Hi,  drop_path is very important and is loaded into the model (you can try
to print the drop_path), and clip_grad is only active in the base size
model.

imcjx ***@***.***> 于2022年4月30日周六 17:45写道：
